### ISSUE TITLE
[Bug] Level Emitter causes extreme TPS drop when using Deep Item Storage Disks

### ISSUE THREAD

**Issue by colbiedison** [Technici4n/AE2Things-Forge#12]
### Describe the bug
When using 256k disks which have a large amount of items in them, level emitters become extremely slow and gradually eat more tick time as more items are added to the network.
### How to reproduce the bug
I managed to reproduce the bug in FTB Stoneblock 3 by:
- creating a network with a few drive blocks 
- filling up all but one of them
- then importing a bunch of random items from a mob farm.

It seems to require items to be flowed in gradually, and it seems to prefer large numbers of different types of items. In the level emitter, I set it to an item which the system has a lot of. I also set the threshold number to a high value.

In my singleplayer world where I first encountered the bug, the item was Certus Quartz Crystals and the value was 131,072 (2^17).
### Expected behavior
The drives + level emitter should not take so much tick time.
### Additional details
Modpack: FTB StoneBlock 3 1.5.0
OS: Linux 6.1
Ryzen 7 5700X / 32 GB RAM
Java: openjdk 17.0.1 2021-10-19 (Termurin)
Minecraft 1.18.2
Forge 40.1.92
AE2 11.7.0
AE2 Things 1.0.4

I was unable to reproduce the bug using regular AE2 drives.

Spark profile: https://spark.lucko.me/vzy1uXOEpS

Video of the bug in my singleplayer world: 

https://user-images.githubusercontent.com/46203390/211126950-8331f4e3-6fac-4cbf-87ae-3751d1322323.mp4

Video of my reproduction in creative mode:

https://www.youtube.com/watch?v=c2tMSAQjjNI
The EMC links were for testing and don't seem to affect anything.

**Comment by Technici4n** [comment]
Thanks a lot for the detailed and excellent report. This issue occurs when having large amounts of NBT data, and should be addressed by AppliedEnergistics/Applied-Energistics-2#6885. I'll backport and release that fix shortly.

**Comment by Technici4n** [comment]
Well that took a while, but the very latest version of AE2 (11.7.2 on 1.18.2) should help a lot.
