### ISSUE TITLE
Mod Crash

### ISSUE THREAD

**Issue by FooterMan14** [Technici4n/AE2Things-Forge#13]
AE2T on 1.19.2 stops world loading with a crash. I have been able to reproduce with the addon on it's own with AE2. [latest.log](https://gist.github.com/FooterMan14/5c71f01184b80f0a474b5cc2b316df3b) [crash log](https://gist.github.com/FooterMan14/ae9eaad3c9251e0da7db13a13a56126b)

**Comment by FooterMan14** [comment]
The Invalid Player Data issue was meant for something else, whoops. Just a crash.

**Comment by choombdev** [comment]
Getting the same crash on 1.18.2, I'm assuming this is related to the Forge update since downgrading from V40.2.1 to V40.2.0 worked, unsure what versions would work on 1.19.2 though.

**Comment by FoxMcloud5655** [comment]
Can confirm that it crashes on Forge 40.2.1 and works correctly in Forge 40.2.0.  The update for this version of Forge includes the following text:
`Fire TickEvent.WorldTickEvent on ClientLevel tick (#9304)`
The same "fix" is applied to Forge 43.2.4 for Minecraft 1.19.2, so downgrading to version 43.2.3 would be your best bet, @FooterMan14.

**Comment by FooterMan14** [comment]
Awesome, thank you.

**Comment by Technici4n** [comment]
Thanks @FoxMcloud5655 for explaining the fix, this saved me a lot of time and motivated me to fix it quickly as it's a simple fix.

The fixed 1.0.5 and 1.1.1 AE2 for 1.18.2 and 1.19.2 respectively are building as we speak.

**Comment by FoxMcloud5655** [comment]
Of course!  Always happy to help a fellow mod developer out.
