### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by qQuazed** [Technici4n/AE2Things-Forge#15]
![image](https://user-images.githubusercontent.com/129326735/228641736-ad971a42-c0d7-400d-aa13-0a239970a864.png)
https://mclo.gs/gdHFYg6

The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing from class net.mehvahdjukaar.modelfix.ModelFix (net.minecraft.client.renderer.block.model.ItemModelGenerator$SpanFacing is in module minecraft@1.19.2 of loader 'TRANSFORMER' @2df3545d; net.mehvahdjukaar.modelfix.ModelFix is in module modelfix@1.8 of loader 'TRANSFORMER' @2df3545d)

Exit code: -1

**Comment by Technici4n** [comment]
This has nothing to do with AE2T.
