### ISSUE TITLE
Cannot Upgrade DISKs in the cell workbench

### ISSUE THREAD

**Issue by a1qs** [Technici4n/AE2Things-Forge#17]
Using the version: `AE2-Things-1.0.5.jar` on 1.18.2
Putting the DISK into a cell drive will display that it cannot be upgrade by any upgrades provided by AE2, which includes Fuzzy upgrades and any of the similar.

**Comment by Technici4n** [comment]
I think Fuzzy and Inverter upgrades make sense for DISKs. Equal Distribution and Overflow Destruction should be left for AE2 cells, they don't make sense for DISKs. (Just use AE2 cells if you want these upgrades).
