### ISSUE TITLE
Advanced Inscriber Automation Issues

### ISSUE THREAD

**Issue by SquidWhisperer** [Technici4n/AE2Things-Forge#2]
This mod is installed as a part of All the Mods 7, and I just started setting up some automation for AE2 circuits. However, I've noticed some things. Firstly, there is no option to lock slots within the machine. Additionally, while setting up my final assembly inscriber, using an exporter to keep the advanced inscriber stocked with printed silicon will fill both the top and bottom slots in the machine, regardless as to which face of the block the export bus is placed. Workarounds include not using the advanced inscriber specifically for the final assembly of processors, or by having an advanced inscriber dedicated to each of the 3 processors, with level emitters. Some level of control as to which face of the machine is tied to a certain input slot would be appreciated.

**Comment by minenine** [comment]
the advanced inscriber is not part of Applied Energistics 2 mod, its is a addon.

**Comment by ProjectET** [comment]
? this this the ae2things repo not the ae2 repo. This is the correct place for opening an issue for the advanced inscriber

**Comment by minenine** [comment]
oh lamo i saw it on the discord and thought that was only linked to the AE2 one did not even think to check XD my b
