### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by castilio20** [Technici4n/AE2Things-Forge#22]
Right now the cell dont rlly work with the cell workbench as in they dont accept upgrades like fuzzy cards

**Comment by castilio20** [comment]
![2023-08-17_12 26 47](https://github.com/Technici4n/AE2Things-Forge/assets/76228548/469468e5-0586-4b32-bb91-d9e21abd26a6)
it seems you added them at least in 1,20

**Comment by Technici4n** [comment]
Ah yes - you are right... :smile:

**Comment by castilio20** [comment]
![2023-06-21_22 30 33](https://github.com/Technici4n/AE2Things-Forge/assets/76228548/ad053f81-6a57-4dfa-acb6-da0594dc861d)
Last time i used that feature was 1.18 on vault hunters and forgot to check the new version
back then i used that to filter the cells
