### ISSUE TITLE
Crash after implementing shader stuff

### ISSUE THREAD

**Issue by Snipe13051** [Technici4n/AE2Things-Forge#23]
Hi, after i implemented the following mods (check screenshot) i got this error: 

[crash-2023-08-20_11.51.38-client.txt](https://github.com/Technici4n/AE2Things-Forge/files/12387895/crash-2023-08-20_11.51.38-client.txt)
![new mods](https://github.com/Technici4n/AE2Things-Forge/assets/16709493/c82b09e6-f57e-478b-a380-409c9c71e898)

**Comment by Technici4n** [comment]
Update to 1.0.5.

**Comment by Snipe13051** [comment]
Thanks for the fast help and reply. :)
