### ISSUE TITLE
advanced inscriber

### ISSUE THREAD

**Issue by pyscho974** [Technici4n/AE2Things-Forge#24]
while playing ATM 8. the advanced inscriber is not allowing the presses to be output with any AE2 possibilities.
once i pull the presses out manually the inscriber continues on with its crafting till it issues another press and locks up.

when running autocrafting the system claims it needs 9 presses when crafting 10 logic processors  or 99 if try for 100. not sure why would need so many presses for a repeat crafting.  only thing i can do to fix is go to original inscriber of AE 2 at this point

**Comment by Technici4n** [comment]
You can specify the press as a secondary output and it will be reused.

**Comment by pyscho974** [comment]
import bus not pulling the press and setting as a secondary output not auotmatic eject . so unless im missing something in the setup.. everything gets put into the advanced inscribe.. everything but the press is pulled out .. locking up the press .. ive even tried every side to import the press from and does not work. its just locked into its spot once its inserted there. interface on the top. import on the front and a pattern provider on the right side.
