### ISSUE TITLE
[Question] How to I recover the UUID for a DISK?

### ISSUE THREAD

**Issue by levicc00123** [Technici4n/AE2Things-Forge#25]
So I lost a 256k DISK that had a lot of stuff on it, thankfully I still have the disk_manager.dat file in my save's data folder. I've tried looking at disk_manager.dat with NBTExplorer, and it's not obvious what I'm looking at when I open the diskuuid entry. Thank you for reading this.

**Comment by ramidzkh** [comment]
Give yourself a DISK with the same UUID as the entry in disk_manager.dat. Join the AE2 discord server if you need more help

**Comment by levicc00123** [comment]
Thank you very much!
