### ISSUE TITLE
Request for Adding an Unlimited Storage Disk

### ISSUE THREAD

**Issue by gjmhmm8** [Technici4n/AE2Things-Forge#36]
I am writing to suggest the addition of an unlimited storage disk feature to your awesome AE2Things project. This feature would be extremely useful for users like me who require extensive storage capabilities for their projects.
With the current limitations on disk storage, it can be quite challenging to work on large-scale projects without running into issues. By implementing an unlimited storage disk, users will have the flexibility to work on their projects without worrying about running out of storage space.
Furthermore, this feature would also be beneficial for users who need to store and manage large amounts of data for their applications or experiments. It would greatly enhance the overall user experience and make AE2Things an even more powerful tool for developers and researchers.
I understand that implementing such a feature may come with its own set of challenges, but I believe that the benefits it would bring to the users would be well worth the effort.
Thank you for considering my suggestion, and I look forward to seeing the enhancements that AE2Things will bring in the future!

**Comment by gjmhmm8** [comment]
[src.zip](https://github.com/Technici4n/AE2Things-Forge/files/14609113/src.zip)

**Comment by Sea-Kerman** [comment]
The bulk cell from MEGA uses BigInteger, which is effectively infinite. It’s so big it would take millions of times the age of the universe to fill it.

**Comment by Technici4n** [comment]
I will not add larger DISKs because more types generally means more lag. It would lead to disastrous performance. For a single type, you can indeed use a bulk cell from MEGA.

**Comment by gjmhmm8** [comment]
A larger number of items will not cause an increase in delays, and the type of items can be determined by simple performance tests to avoid excessive delays.

**Comment by gjmhmm8** [comment]
@Technici4n

**Comment by Technici4n** [comment]
More types will cause performance issues, that is just a fact given how mods like AE2 work.

**Comment by gjmhmm8** [comment]
This is true, but you can impose certain limitations on the types to some extent (such as 10,000 or determined by a simple performance test). At the same time, you can lift the restrictions on the quantity of items, as the impact of item quantity on performance is minimal (when the current limit is not in place, the number of available types far exceeds 10,000, and this can lead to serious performance issues).

**Comment by 62832** [comment]
Please stop using AI to generate your responses to an already rejected feature request. We're not adding unlimited storage disks.

**Comment by gjmhmm8** [comment]
I am not good at English so I use ai to translate

**Comment by gjmhmm8** [comment]
You don’t have to add it if you don’t want to in your mod.
@62832
