### ISSUE TITLE
ae2 things storage disks on all the mods 7 have stopped working

### ISSUE THREAD

**Issue by chunkyrabbit32** [Technici4n/AE2Things-Forge#6]
So recently my ae2 things storage drives have stopped working, i have disks with many items on but when i put the disk drive into my me drive they appear green and dont show the items in the grid anywhere .Just wondering if there is a fix.

**Comment by Technici4n** [comment]
That's an AE2 bug I'm pretty sure. Should be fixed in the next AE2 release.
